name: CI-CD

on:
  push:

jobs:
  test:
    name: Unit Test
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Unit Tests
        run: nix develop .#ci -c ./scripts/ci/test.sh
  precommit:
    name: Pre-commit Check
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh
  release:
    name: Semantic Release Helm Chart
    needs:
      - test
      - precommit
    if: github.ref == 'refs/heads/main'
    runs-on:
      - ARM64
      - nix
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
          fetch-depth: 0
      - name: Inject Github Variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
        run: nix develop .#ci -c scripts/ci/release.sh
