name: CI-CD

on:
  push:

jobs:
  test:
    name: Unit Test
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Unit Tests
        run: nix develop .#ci -c ./scripts/ci/test.sh
  precommit:
    name: Pre-commit Check
    runs-on:
      - nix
      - ARM64
    steps:
      - name: Gotrade CI Environment
        uses: kirinnee/atomici-action@v2.3.1
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run pre-commit
        run: nix develop .#ci -c ./scripts/ci/pre-commit.sh
